rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ruby-head
  - jruby
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby

bundler_args: --without guard docs

script: bundle exec rspec spec/ -b
